# -*- coding: utf-8 -*-
"""Desafio_uno_agentes_IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2-UjaaPAZqwEqWZp1qosHlcbp-1zwmu

# Conexión con LLMs
"""

!pip install -q langchain langchain-google-genai google-generativeai

from google.colab import userdata
GEMINI_API_KEY = userdata.get('GEMINI_API_KEY')

from langchain_google_genai import ChatGoogleGenerativeAI

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=2,
    google_api_key=GEMINI_API_KEY
)

respuesta = llm.invoke("en cinco líneas, ¿Qué es negocio de e-commerce?")

respuesta.content
