# -*- coding: utf-8 -*-
"""Desafio_uno_agentes_IA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u2-UjaaPAZqwEqWZp1qosHlcbp-1zwmu

# Conexión con LLMs
"""

!pip install -q langchain langchain-google-genai google-generativeai

!pip install -q groq langchain-groq

from google.colab import userdata
import os

os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')

from langchain_groq import ChatGroq

llm = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=1
)

respuesta = llm.invoke("en cinco líneas, ¿Qué es negocio de e-commerce?")

respuesta.content
